version: "3.3"
services:
  phoenix:
    build: ./API
    depends_on:
      - db
    ports:
      - "4000:4000"
    command: /bin/bash -c "source ./entrypoint.sh"
    networks:
      - back_net
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - ./docker-entrypoint-initdb.d/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks: 
      - back_net
volumes:
  postgres_data:

networks:
  back_net:
    driver: bridge
